# Generated by Django 4.1.7 on 2023-03-08 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=80, verbose_name='Username')),
                ('password', models.CharField(max_length=300, verbose_name='Password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super User')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=100, verbose_name='Denomination')),
            ],
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing', models.CharField(max_length=100, verbose_name='Wing')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church', verbose_name='Church')),
                ('users', models.ManyToManyField(through='core.Due', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='due',
            name='wing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wing', verbose_name='Wing'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_wing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wing_user_set', to='core.wing', verbose_name='Wing'),
        ),
        migrations.AddField(
            model_name='user',
            name='wings',
            field=models.ManyToManyField(through='core.Due', to='core.wing'),
        ),
    ]
