# Generated by Django 4.1.7 on 2023-03-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            ("INSERT INTO core_church (denomination) VALUES ('Default Church');"),
            ("DELETE FROM core_church WHERE denomination = 'Default Church';")
        ),
    ]
