# Generated by Django 4.1.7 on 2023-03-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230308_0948'),
    ]

    operations = [
        migrations.RunSQL(
            ("INSERT INTO core_wing (wing, church_id) VALUES ('Default Wing', 1);"),
            ("DELETE FROM core_wing WHERE wing = 'Default Wing' and church_id = 1;")
        )
    ]
